In [ ]:
import numpy as np


In [ ]:
A = np.array([[1,2,3],[4,5,6]])
print(A)

[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[7,8,9],[10,11,12]])
print("Matrix A : \n",A)
print("Matrix B : \n",B)


Matrix A : 
 [[1 2 3]
 [4 5 6]]
Matrix B : 
 [[ 7  8  9]
 [10 11 12]]


In [ ]:
print("Addition: \n", A + B)

Addition: 
 [[ 8 10 12]
 [14 16 18]]


In [ ]:
print("Subtraction: \n", B - A)

Subtraction: 
 [[6 6 6]
 [6 6 6]]


In [ ]:
print("Mutiplication: \n", A * B)

Mutiplication: 
 [[ 7 16 27]
 [40 55 72]]


In [ ]:
print("\nDot Product:\n", np.dot(A, B.T))


Dot Product:
 [[ 50  68]
 [122 167]]


In [ ]:
print("\nTranspose:\n", A.T)


Transpose:
 [[1 4]
 [2 5]
 [3 6]]


In [ ]:
import random


In [ ]:
random.random()

0.36668202238539704

In [ ]:
a=1
b=20


In [ ]:
random.randint(a,b)

1

In [ ]:
random.uniform(a,b)

10.619633453947115

In [ ]:
random.choice(['apple','mango','banana'])

'banana'

In [ ]:
random.sample([10,20,30,40,50], 2)

[50, 20]

In [ ]:
names = ["Antara", "Ravi", "Sneha", "Kiran"]

random.shuffle(names)

In [ ]:
random.seed(10)
random.randint(1,100)

74

In [ ]:
import pandas as pd
data = pd.read_csv("sales_sample.csv")
display(data.head())


,Customer_ID,City,Product,Sales
0,1,Delhi,Pen,100
1,2,Mumbai,Book,250
2,3,Patna,Bottle,150
3,4,Delhi,Notebook,300
4,5,Pune,Bag,500


In [ ]:
display(data.tail())


,Customer_ID,City,Product,Sales
5,6,Delhi,Pen,80
6,7,Mumbai,Book,270
7,8,Patna,Pen,90
8,9,Pune,Bottle,400
9,10,Delhi,Notebook,350


In [ ]:
display(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   Customer_ID  10 non-null     int64 
 1   City         10 non-null     object
 2   Product      10 non-null     object
 3   Sales        10 non-null     int64 
dtypes: int64(2), object(2)
memory usage: 452.0+ bytes


None

In [ ]:
display(data.describe)

<bound method NDFrame.describe of    Customer_ID    City   Product  Sales
0            1   Delhi       Pen    100
1            2  Mumbai      Book    250
2            3   Patna    Bottle    150
3            4   Delhi  Notebook    300
4            5    Pune       Bag    500
5            6   Delhi       Pen     80
6            7  Mumbai      Book    270
7            8   Patna       Pen     90
8            9    Pune    Bottle    400
9           10   Delhi  Notebook    350>